name: ðŸ—ï¸ CI/CD Launcher

on:
  # Allow manual dispatch with a buildType input
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type: 'preview' for manual/dev builds, 'release_candidate' for staging (e.g., v1.2.3-rc.1), 'release' for production (e.g., v1.2.3)"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - release_candidate
          - release
      skipTests:
        description: "Whether tests should be skipped"
        required: true
        default: "false"
        type: choice
        options:
          - 'true'
          - 'false'
      deployTargets:
        description: "JSON array of deploy targets (e.g. [\"itch.io\",\"s3\"])"
        required: true
        default: '["steam", "gh-pages"]'
        type: string
      version:
        description: Optional version override
        type: string
        required: false
  # Automatically run tests & builds on certain branches or PR changes
  push:
    branches-ignore:
      - 'main'
      - 'master'
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
  pull_request:
    types: [ready_for_review, synchronize, reopened]
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  skip_ci:
    name: Check Skip CI triggers
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check last commit for [skip ci]   
        id: check
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MSG"

          if [[ "$COMMIT_MSG" == *"[skip ci]"* || "$COMMIT_MSG" == *"[ci skip]"* ]]; then
            echo "Skipping CI as requested."
            echo "should_run=false" >> "$GITHUB_OUTPUT"
          else
            echo "Proceeding with CI."
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          fi

  validate_vars:
    name: Validate GitHub Variables
    needs: skip_ci
    if: ${{ needs.skip_ci.outputs.should_run == 'true'}}
    uses: avalin/unity-ci-templates/.github/workflows/validate-github-vars.yml@main
    with:
      requiredVars: |
        [
          "COMBINE_ARTIFACTS",
          "DEPLOY_TARGETS",
          "EXCLUDE_UNITY_TESTS",
          "PROJECT_NAME",
          "RETENTION_DAYS_PREVIEW",
          "RETENTION_DAYS_RELEASE",
          "TARGET_PLATFORMS_PREVIEW",
          "TARGET_PLATFORMS_RELEASE"
        ]

  prepare_metadata:
    name: Prepare Metadata
    needs: 
      - validate_vars
      - skip_ci
    if: ${{ needs.skip_ci.outputs.should_run == 'true'}}
    uses: ./.github/workflows/prepare-metadata.yml
    with:
      skipTests: ${{ inputs.skipTests || vars.EXCLUDE_UNITY_TESTS}}
      deployTargets: ${{ inputs.deployTargets || vars.DEPLOY_TARGETS }}
      buildType: ${{ inputs.buildType }}
      version: ${{ inputs.version }}
  
  trigger_ci:
    name: Trigger CI/CD Pipeline
    needs: 
      - prepare_metadata
      - skip_ci
    if: ${{ needs.skip_ci.outputs.should_run == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Trigger downstream pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_PAT }}
        run: |
          gh workflow run ci-cd-pipeline.yml \
            --ref "${{ github.ref }}" \
            --field triggeredBy="${{ needs.prepare_metadata.outputs.triggeredBy }}" \
            --field skipTests="${{ needs.prepare_metadata.outputs.skipTests }}" \
            --field testsOnly="${{ needs.prepare_metadata.outputs.testsOnly }}" \
            --field buildType="${{ needs.prepare_metadata.outputs.buildType }}" \
            --field version="${{ needs.prepare_metadata.outputs.version }}" \
            --field validDeployTargets="$(printf '%s' '${{ needs.prepare_metadata.outputs.validDeployTargets }}')" \
            --field requiresCombined="${{ needs.prepare_metadata.outputs.requiresCombined }}" \
            --field skipPerPlatform="${{ needs.prepare_metadata.outputs.skipPerPlatform }}"