name: ‚è≥ CI/CD Prerequisites

on:
  workflow_call:
    inputs:
      excludesUnityTests:
        description: "Whether unity tests are excluded"
        type: string
        required: true
jobs:
  validate-vars:
    name: Validate GitHub Variables
    uses: avalin/unity-ci-templates/.github/workflows/validate-github-vars.yml@main
    with:
      requiredVars: |
        [
          "COMBINE_ARTIFACTS",
          "DEPLOY_TARGETS",
          "EXCLUDE_UNITY_TESTS",
          "PROJECT_NAME",
          "RETENTION_DAYS_PREVIEW",
          "RETENTION_DAYS_RELEASE",
          "TARGET_PLATFORMS_PREVIEW",
          "TARGET_PLATFORMS_RELEASE"
        ]

  upload-license:
    name: üì•Ô∏è Upload Unity License
    if: ${{ inputs.excludesUnityTests == 'false' }}
    uses: ./.github/workflows/unity-license-uploader.yml
    secrets: inherit