name: ğŸ“‹ Step 1 - Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
  pull_request:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'

env:
  UNITY_VERSION: '2022.3.60f1'
  LICENSE_ARTIFACT_NAME: 'unity-license'
  USE_GIT_LFS: 'false'

jobs:
  detect-tests:
    name: ğŸ” Detect Tests
    uses: ./.github/workflows/detect-unity-tests.yml
    with:
      editModePath: Assets/Tests/Editor
      playModePath: Assets/Tests/PlayMode

  upload-license:
    name: ğŸ“¥ï¸ Upload Unity License
    needs: detect-tests
    if: needs.detect-tests.outputs.has_editmode == 'true' || needs.detect-tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/upload-unity-license.yml  
    with:
      artifactName: unity-license
    secrets: inherit

  run-editmode:
    name: ğŸ¥ª EditMode Tests
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_editmode == 'true'
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: EditMode
      licenseArtifactName: ${{ env.LICENSE_ARTIFACT_NAME }}
      unityVersion: ${{ env.UNITY_VERSION }}
      useGitLfs: ${{ env.USE_GIT_LFS }}
    secrets: inherit

  run-playmode:
    name: ğŸ® PlayMode Tests
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: PlayMode
      licenseArtifactName: ${{ env.LICENSE_ARTIFACT_NAME }}
      unityVersion: ${{ env.UNITY_VERSION }}
      useGitLfs: ${{ env.USE_GIT_LFS }}
    secrets: inherit