name: âœ¨ Step 2 - Build

on:
  workflow_call:
    inputs:
      projectName:
        description: "The name of the built project i.e. 'My_Project' (avoid spaces)"
        default: "My_Project"
        type: string
        required: false
      buildType:
        description: "Build type, e.g. 'preview' or 'release'"
        type: string
        required: true
      targetPlatforms:
        description: "JSON array of platforms to build"
        type: string
        default: '["Android","WebGL","StandaloneLinux64","StandaloneWindows","StandaloneWindows64","StandaloneOSX","iOS"]'
        required: false
      timeoutMinutes:
        description: "Timeout for each build job in minutes"
        type: number
        default: 30
        required: false
      retentionDays:
          description: "How many days to keep the uploaded build artifacts (e.g. 7 for preview, 30 for release)"
          type: number
          default: 7
          required: false
    secrets:
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true
      UNITY_LICENSE:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filter_platforms:
    uses: ./.github/workflows/target-platforms-filter.yml
    with:
      targetPlatforms: ${{ inputs.targetPlatforms }}

  determine_version:
    uses: ./.github/workflows/build-version-generator.yml
    with:
      buildType: ${{ inputs.buildType }}

  build_on_macos:
    name: Build for ${{ matrix.targetPlatform }}
    if: needs.filter_platforms.outputs.macPlatforms != '[]'
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ inputs.timeoutMinutes }}
    needs: [filter_platforms, determine_version]
    strategy:
      fail-fast: false
      matrix:
        os: 
          - macOS-latest
        targetPlatform: ${{ fromJson(needs.filter_platforms.outputs.macPlatforms) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Unity Library Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.buildType }}-${{ inputs.projectName }}-${{ matrix.targetPlatform }}-${{ needs.determine_version.outputs.version }}
          path: build/${{ matrix.targetPlatform }}
          retention-days: ${{ inputs.retentionDays }}

  build_on_ubuntu:
    name: Build for ${{ matrix.targetPlatform }}
    if: needs.filter_platforms.outputs.ubuntuPlatforms != '[]'
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ inputs.timeoutMinutes }}
    needs: [filter_platforms, determine_version]
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
        targetPlatform: ${{ fromJson(needs.filter_platforms.outputs.ubuntuPlatforms) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Unity Library Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-

      - name: Check Free Disk Space (Android only)
        if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.buildType }}-${{ inputs.projectName }}-${{ matrix.targetPlatform }}-${{ needs.determine_version.outputs.version }}
          path: build/${{ matrix.targetPlatform }}
          retention-days: ${{ inputs.retentionDays }}

  confirm_builds:
    name: ðŸ“„ Summarize Build Results
    runs-on: ubuntu-latest
    needs:
      - build_on_ubuntu
      - build_on_macos
      - filter_platforms
    if: always()
    steps:
      - name: Write Build Summary
        run: |
          echo "### ðŸ“¦ Unity Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "#### ðŸ§ Ubuntu Platforms Attempted:" >> $GITHUB_STEP_SUMMARY
          echo "${{ join(fromJson(needs.filter_platforms.outputs.ubuntuPlatforms), ', ') }}" >> $GITHUB_STEP_SUMMARY
          echo "- Build Status: ${{ needs.build_on_ubuntu.result == 'success' && 'âœ… Success' || 'âŒ Failed or Skipped' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "#### ðŸ macOS Platforms Attempted:" >> $GITHUB_STEP_SUMMARY
          echo "${{ join(fromJson(needs.filter_platforms.outputs.macPlatforms), ', ') }}" >> $GITHUB_STEP_SUMMARY
          echo "- Build Status: ${{ needs.build_on_macos.result == 'success' && 'âœ… Success' || 'âŒ Failed or Skipped' }}" >> $GITHUB_STEP_SUMMARY
