name: âœ¨ Step 2 - Build

on:
  workflow_call:
    inputs:
      buildType:
        description: "Build type, e.g. 'preview' or 'release'"
        type: string
        required: true
      targetPlatforms:
        description: "JSON array of platforms to build"
        type: string
        default: '["Android","WebGL","StandaloneLinux64","StandaloneWindows","StandaloneWindows64","StandaloneOSX","iOS"]'
        required: false
    secrets:
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true
      UNITY_LICENSE:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filter_platforms:
    name: Filter Platforms
    runs-on: ubuntu-latest
    outputs:
      macPlatforms: ${{ steps.filter.outputs.macPlatforms }}
      ubuntuPlatforms: ${{ steps.filter.outputs.ubuntuPlatforms }}

    steps:
      - name: Separate Selected Platforms Into Outputs
        id: filter
        run: |
          echo "Original input: ${{ inputs.targetPlatforms }}"

          MAC_PLATFORMS=$(echo '${{ inputs.targetPlatforms }}' \
            | jq -c '[ .[] | select(. == "StandaloneOSX" or . == "iOS") ]')
          UBUNTU_PLATFORMS=$(echo '${{ inputs.targetPlatforms }}' \
            | jq -c '[ .[] | select(. != "StandaloneOSX" and . != "iOS") ]')

          echo "Mac platforms: $MAC_PLATFORMS"
          echo "Ubuntu platforms: $UBUNTU_PLATFORMS"

          echo "macPlatforms=$MAC_PLATFORMS" >> $GITHUB_OUTPUT
          echo "ubuntuPlatforms=$UBUNTU_PLATFORMS" >> $GITHUB_OUTPUT

  build_on_macos:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ${{ matrix.os }}
    needs: filter_platforms
    strategy:
      matrix:
        os: 
          - macOS-latest
        targetPlatform: ${{ fromJson(needs.filter_platforms.outputs.macPlatforms) }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Unity Library Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-${{ matrix.targetPlatform }}-
        
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}-${{ env.VERSION }}
          path: build/${{ matrix.targetPlatform }}
    
  build_on_ubuntu:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ${{ matrix.os }}
    needs: filter_platforms
    strategy:
      matrix:
        os: 
          - ubuntu-latest
        targetPlatform: ${{ fromJson(needs.filter_platforms.outputs.ubuntuPlatforms) }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Unity Library Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-${{ matrix.targetPlatform }}-

      - name: Check Free Disk Space (Android only)
        if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
        
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}-${{ env.VERSION }}
          path: build/${{ matrix.targetPlatform }}
  
  confirm_builds:
    name: Confirm Builds
    runs-on: ubuntu-latest
    needs: 
      - build_on_ubuntu
      - build_on_macos
    steps:
      - name: Confirm Builds
        run: echo "Creating builds successfully finished!"