name: ğŸ“‹ Step 1 - Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
    paths-ignore:
      - '**.md'
      - '.github/README.md'
  pull_request:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'

jobs:
  detect-tests:
    name: ğŸ” Detect Tests
    uses: ./.github/workflows/detect-unity-tests.yml
    with:
      editModePath: Assets/Tests/Editor
      playModePath: Assets/Tests/PlayMode

  upload-license:
    name: â™»ï¸ Upload Unity License
    needs: detect-tests
    if: needs.detect-tests.outputs.has_editmode == 'true' || needs.detect-tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/upload-unity-license.yml  
    with:
      artifactName: unity-license
    secrets: inherit

  run-editmode:
    name: ğŸ¥ª EditMode Tests
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_editmode == 'true'
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: EditMode
      licenseArtifactName: 'unity-license'
    secrets: inherit

  run-playmode:
    name: ğŸ® PlayMode Tests
    needs: [detect-tests, upload-license]
    if: needs.detect-tests.outputs.has_playmode == 'true'
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: PlayMode
      licenseArtifactName: 'unity-license'
    secrets: inherit