name: ğŸ“Š Step 1 - Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'
  pull_request:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
      - 'Tests/**'

jobs:
  upload-license:
    name: â™»ï¸ Upload Unity License
    uses: ./.github/workflows/unity-license-upload.yml
    secrets: inherit

  run-editmode:
    name: ğŸ§ª EditMode Tests
    needs: upload-license
    if: needs.upload-license.result == 'success' && <your other condition>
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: EditMode
    secrets: inherit

  run-playmode:
    name: ğŸ® PlayMode Tests
    needs: upload-license
    if: needs.upload-license.result == 'success' && <your other condition>
    uses: ./.github/workflows/unity-test-runner.yml
    with:
      testMode: PlayMode
    secrets: inherit

