# .github/workflows/step-0-roslyn-analyze.yml
name: ðŸ§  Step 0 - Roslyn Lint (CSharpier)

on:
  workflow_call:

jobs:
  roslyn-lint:
    name: ðŸ§  C# Code Lint (No MSBuild)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install and Run CSharpier
        run: |
          echo "ðŸ“‚ Installing & Scanning Assets..."
          dotnet tool install -g csharpier
          ~/.dotnet/tools/csharpier --check Assets


