name: üß™ Test Build & Release Workflow

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Type of build: 'preview' or 'release'"
        required: true
        default: "preview"
      version:
        description: "Version string (e.g. v0.1.2 or v0.1.2-preview)"
        required: true
        default: "v0.1.2-test"
      projectName:
        description: "Project name for artifacts"
        required: true
        default: "Unity_CI_Templates"
      targetPlatforms:
        description: "JSON array of platforms to build"
        required: true
        default: '["WebGL", "StandaloneWindows64"]'
      deployTargets:
        description: "JSON array of deploy targets (e.g. ['itch.io','s3'])"
        required: false
        default: '[]'

jobs:
  setup-prerequisites:
    name: ‚è≥ Setup Prerequisites
    uses: avalin/unity-ci-templates/.github/workflows/ci-cd-prerequisites.yml@main
    with:
      excludesUnityTests: "true"
      deployTargets: ${{ inputs.deployTargets }}
    secrets: inherit

  build:
    name: üß© Trigger Unity Build (Step 2)
    needs: setup-prerequisites
    uses: ./.github/workflows/step-2-build.yml
    with:
      buildType: ${{ inputs.buildType }}
      projectName: ${{ inputs.projectName }}
      targetPlatforms: ${{ inputs.targetPlatforms }}
      combineArtifacts: ${{ fromJSON(needs.setup-prerequisites.outputs.requiresCombinedArtifact) }}
    secrets: inherit

  release:
    name: üì¶ Trigger GitHub Release (Step 3)
    if: ${{ inputs.buildType == 'release' }}
    needs: [ setup-prerequisites, build ]
    uses: ./.github/workflows/step-3-release.yml
    with:
      buildType: ${{ inputs.buildType }}
      version: ${{ needs.build.outputs.version }}
      projectName: ${{ inputs.projectName }}
      targetPlatforms: ${{ inputs.targetPlatforms }}
      combineArtifacts: ${{ needs.setup-prerequisites.outputs.requiresCombinedArtifact }}
      skipPerPlatformArtifacts: ${{ needs.setup-prerequisites.outputs.skipPerPlatformArtifacts }}
    secrets: inherit
