name: ðŸ§ª Test Deploy & Notify Workflows

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type: 'release_candidate' | 'release'"
        required: true
        default: "release_candidate"
        type: choice
        options:
          - release_candidate
          - release
      version:
        description: "The GitHub release tag (e.g. v0.1.2-ekans)"
        required: true
      projectName:
        description: "Project name used in the release file naming (e.g. Unity_CI_Templates)"
        default: "Unity_CI_Templates"
        required: true
      deployTargets:
        description: "JSON array of deploy targets"
        default: '["gh-pages"]'
        required: true
      releaseResult:
        description: "Whether release should show as a success or a failure"
        default: "success"
        required: true
        type: choice
        options:
          - success
          - failure
      testNotify:
        description: "Whether notifications needs to be tested too"
        required: false
        default: "false"
        type: choice
        options:
          - true
          - false

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare_metadata:
    name: â³ Prepare Metadata
    uses: ./.github/workflows/prepare-metadata.yml
    with:
      skipTests: true
      skipBuild: true
      testsOnly: false
      deployTargets: ${{ inputs.deployTargets }}
      buildType: ${{ inputs.buildType }}
      version: ${{ inputs.version }}

  test_deploy:
    name: Test Deploy
    needs: [ prepare_metadata ]
    uses: avalin/unity-ci-templates/.github/workflows/step-4-deploy.yml@main
    with:
      buildType: release
      version: ${{ inputs.version }}
      projectName: ${{ inputs.projectName }}
      deployTargets: ${{ needs.prepare_metadata.outputs.validDeployTargets }}
      hasCombinedArtifacts: ${{ needs.prepare_metadata.outputs.requiresCombined }}
      artifactSource: release
    secrets: inherit

  test_notify:
    name: Test Notify
    uses: avalin/unity-ci-templates/.github/workflows/step-5-notify.yml@main
    if: >
      always() &&
      (needs.test_deploy.result == 'success' || needs.test_deploy.result == 'failure') &&
      inputs.testNotify == 'true'
    needs: [ test_deploy ]
    with:
      releaseResult: ${{ inputs.releaseResult }}
      releaseErrorMessage: ""
      deployResult: ${{ needs.test_deploy.result }}
      version: ${{ inputs.version }}
    secrets: inherit