name: ‚ôªÔ∏è Upload Unity License

on:
  workflow_call:
    inputs:
      artifactName:
        default: 'unity-license'

jobs:
  activate-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate Unity License
        uses: game-ci/unity-activate@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Upload Unity License File
        run: |
          echo "üîç Searching for license file..."
          FOUND=$(find $HOME -type f -name 'Unity_lic.ulf' | head -n 1)
          if [ -z "$FOUND" ]; then
            echo "‚ùå License file not found"
            exit 1
          else
            echo "‚úÖ Found at $FOUND"
            mkdir -p license
            cp "$FOUND" license/
          fi

      - name: Upload License Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactName }}
          path: license/Unity_lic.ulf
          retention-days: 3